version: "3.7"

services:
    deno1:
      image: "deno-server:1.0.0"
      build: .
      ports:
        - "8000:8000"
        - "8080:8080"
      networks: 
        - deno
      environment:
        - SERVER_URL=http://localhost:8000
        - SOCKET_URL=ws://localhost:8080
        - SOCKETS_PRIORITY=ws://localhost:8080,ws://localhost:8081,ws://localhost:8082
        - OTHER_CLUSTER_NODES=http://deno2:8001,http://deno3:8002

    deno2:
      image: "deno-server:1.0.0"
      build: .
      ports:
        - "8001:8001"
        - "8081:8081"
      networks: 
        - deno
      environment:
        - SERVER_URL=http://localhost:8001
        - SOCKET_URL=ws://localhost:8081
        - SOCKETS_PRIORITY=ws://localhost:8080,ws://localhost:8081,ws://localhost:8082
        - OTHER_CLUSTER_NODES=http://deno1:8000,http://deno3:8002

    deno3:
      image: "deno-server:1.0.0"
      build: .
      ports:
        - "8002:8002"
        - "8082:8082"
      networks: 
        - deno
      environment:
        - SERVER_URL=http://localhost:8002
        - SOCKET_URL=ws://localhost:8082
        - SOCKETS_PRIORITY=ws://localhost:8080,ws://localhost:8081,ws://localhost:8082
        - OTHER_CLUSTER_NODES=http://deno1:8000,http://deno2:8001

networks:
  deno: {}